---
title: "Greenwood"
subtitle: "Dashboard"
logo: "logo.png"

header: false
footer: '<p>[iheartmeghan]</p>' 

stylesheet:
  - "assets/custom.css"

columns: "3"
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" 
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "//Media"
    icon: ""
    items:
      - name: "Jellyfin"
        logo: "assets/icons/jellyfin.svg"
        subtitle: "Media Server"
        tag: "vidz"
        tagstyle: "is-primary"
        url: "http://10.0.0.202:8096/web/index.html#!/home.html"
        target: "_blank"
      - name: "Immich"
        logo: "assets/icons/immich.svg"
        subtitle: "Photo and Video Management"
        tag: "picz"
        tagstyle: "is-primary"
        url: "http://10.0.0.202:2283"
        target: "_blank"
      - name: "Nextcloud"
        logo: "assets/icons/nextcloud.svg"
        subtitle: "File and Communication App"
        tag: "filez"
        tagstyle: "is-primary"
        url: "http://10.0.0.202:9876"
        target: "_blank"

  - name: "//Network"
    icon: ""
    items:
      - name: "Pi-Hole"
        logo: "assets/icons/pihole.svg"
        subtitle: "DNS Sinkhole (BerryBox)"
        tag: "adz"
        tagstyle: "is-success"
        url: "http://10.0.0.203:1010/admin/"
        target: "_blank"
      - name: "Netgear"
        logo: "assets/icons/router.svg"
        subtitle: "Router Configuration"
        tag: "routz"
        tagstyle: "is-success"
        url: "http://10.0.0.1/"
        target: "_blank"
  - name: "//Management"
    icon: ""
    items:
      - name: "Portainer"
        logo: "assets/icons/portainer.svg"
        subtitle: "Container Management"
        tag: "containerz"
        tagstyle: "is-info"
        url: "https://10.0.0.202:9443/#!/home"
        target: "_blank"
      - name: "Duplicati"
        logo: "assets/icons/duplicati.svg"
        subtitle: "Backup Client"
        tag: "backupz"
        tagstyle: "is-info"
        url: "http://10.0.0.202:8899/ngax/index.html"
        target: "_blank"
      - name: "Syncthing"
        logo: "assets/icons/syncthing.svg"
        subtitle: "File Synchronization"
        tag: "syncz"
        tagstyle: "is-info"
        url: "http://10.0.0.202:8384/"
        target: "_blank"
  - name: "//Home"
    icon: ""
    items:
      - name: "Grocy"
        logo: "assets/icons/grocy.svg"
        subtitle: "Groceries and Household Management"
        tag: "foodz"
        style: "is-link"
        url: "http://10.0.0.202:9283/shoppinglist"
        target: "_blank"
